// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR-QJMmL5nSt-J5K6FktTAv5_aErUregM',
    appId: '1:867363482583:web:3a3d9d65e3f0ef74d7f992',
    messagingSenderId: '867363482583',
    projectId: 'pomodoropro-211',
    authDomain: 'pomodoropro-211.firebaseapp.com',
    databaseURL: 'https://pomodoropro-211-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pomodoropro-211.firebasestorage.app',
    measurementId: 'G-TQR98R01RR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZgE1IGcM-gT5fndeYz2mMNr4teu2_CZg',
    appId: '1:867363482583:android:9e237af9aaabb01cd7f992',
    messagingSenderId: '867363482583',
    projectId: 'pomodoropro-211',
    databaseURL: 'https://pomodoropro-211-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pomodoropro-211.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw0OUqDC2-mJz7_PXeyy92b7NVJj85wWA',
    appId: '1:867363482583:ios:0d9725ed791aa667d7f992',
    messagingSenderId: '867363482583',
    projectId: 'pomodoropro-211',
    databaseURL: 'https://pomodoropro-211-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pomodoropro-211.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw0OUqDC2-mJz7_PXeyy92b7NVJj85wWA',
    appId: '1:867363482583:ios:0d9725ed791aa667d7f992',
    messagingSenderId: '867363482583',
    projectId: 'pomodoropro-211',
    databaseURL: 'https://pomodoropro-211-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pomodoropro-211.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDR-QJMmL5nSt-J5K6FktTAv5_aErUregM',
    appId: '1:867363482583:web:50df4c7174591b11d7f992',
    messagingSenderId: '867363482583',
    projectId: 'pomodoropro-211',
    authDomain: 'pomodoropro-211.firebaseapp.com',
    databaseURL: 'https://pomodoropro-211-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pomodoropro-211.firebasestorage.app',
    measurementId: 'G-L8PP21MFNM',
  );

}